flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- generator-0.5.5
- cryptohash-sha256-0.11.100.1
- aeson-pretty-0.8.2
# TODO This is requested but should be solved
# by the resolver?
- haddock-api-2.17.4
- hdocs-0.5.2.0
- hformat-0.3.0.0
- simple-log-0.9.2
- text-region-0.3.0.0
resolver: lts-8.19
pvp-bounds: both
build:
  library-profiling: true
  executable-profiling: true
